### ISSUE TITLE
Fail to translate: object is not iterable

### ISSUE THREAD

**Issue by rvi** [GWesley/auto_localize#5]
Hi super great project, really love it, thanks!

I often got this error message and I was wondering if it's something I should do differently?
```
  ..... !! FAILED !! to translate for es: Next = 'NoneType' object is not iterable
```

**Comment by cyphers** [comment]
I get this for about 70% of the strings in the project. It seems like this repo might not be working anymore with modern tools.

**Comment by GWesley** [comment]
I think this has been fixed
