### ISSUE TITLE
error with "%"

### ISSUE THREAD

**Issue by hzlzh** [GWesley/auto_localize#9]
<img width="682" alt="image" src="https://github.com/GWesley/auto_localize/assets/1049575/b6477563-b079-403c-bff0-5e3eee1c6ec0">

**Comment by GWesley** [comment]
I will take a look when I get some time. 
Also, any contributions of pull requests to enhance this project are greatly appreciated.

**Comment by hzlzh** [comment]
This project is great and very helpful, can I have some way to make some donate?

**Comment by GWesley** [comment]
Thank you for your kindness. At the moment, I haven't considered this.

**Comment by GWesley** [comment]
I think this issue has been fixed.
